server:
  port: 9000

application:
  jwt:
    signing-key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:maindb
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile,flyway"
  health:
    defaults:
      enabled: true

logging:
  file:
    name: ./logs/auth.log


