### Create order
POST http://localhost:8081/api/v1/orders
Content-Type: application/json

{
  "userId": 1,
  "items": [{"id": 1}, {"id": 2}, {"id": 3}]
}

### Get order info
GET http://localhost:8081/api/v1/orders/18a0b09a-4828-4f7b-b23c-9b341318ed12

### Cancel order
PATCH http://localhost:8081/api/v1/orders/18a0b09a-4828-4f7b-b23c-9b341318ed12