### Signup user
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "username": "demo_user",
  "password": "demo_password"
}

### Login user
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "demo_user",
  "password": "demo_password"
}

### Create order (without Authorization token)
POST http://localhost:8080/api/v1/orders
Content-Type: application/json

{
  "userId": 1,
  "items": [{"id": 1}, {"id": 2}, {"id": 3}]
}

### Create order (with Authorization token)
POST http://localhost:8080/api/v1/orders
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ1c2VyX2lkIjo0LCJyb2xlIjoiVVNFUiIsInN1YiI6ImRlbW9fdXNlciIsImlhdCI6MTcxMTE5MjYxMCwiZXhwIjoxNzExMTk2MjEwfQ.L8re_0-h_Y8LK6zVUlxhTTd5dTof2cOJcuacP-cXsK5VgE8U1WtvcFc8w9J8mMgp
Content-Type: application/json

{
  "userId": 1,
  "items": [{"id": 1}, {"id": 2}, {"id": 3}]
}


### Get order info
GET http://localhost:8080/api/v1/orders/50137ce9-dfd5-42b4-adf1-0425c3132bae
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ1c2VyX2lkIjo0LCJyb2xlIjoiVVNFUiIsInN1YiI6ImRlbW9fdXNlciIsImlhdCI6MTcxMTE5MjYxMCwiZXhwIjoxNzExMTk2MjEwfQ.L8re_0-h_Y8LK6zVUlxhTTd5dTof2cOJcuacP-cXsK5VgE8U1WtvcFc8w9J8mMgp


### Cancel order
PUT http://localhost:8080/api/v1/orders/50137ce9-dfd5-42b4-adf1-0425c3132bae
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ1c2VyX2lkIjo0LCJyb2xlIjoiVVNFUiIsInN1YiI6ImRlbW9fdXNlciIsImlhdCI6MTcxMTE5MjYxMCwiZXhwIjoxNzExMTk2MjEwfQ.L8re_0-h_Y8LK6zVUlxhTTd5dTof2cOJcuacP-cXsK5VgE8U1WtvcFc8w9J8mMgp
