server:
  port: 8082

application:
  kafka:
    input-topic: "orders"
    output-topic: "orders_processed"
    output-dlq-topic: "orders_failed"

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:maindb
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    consumer:
      group-id: "payments-group"
      auto-offset-reset: earliest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile,flyway"
  health:
    defaults:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: ./logs/payment.log
  level:
    root: info
  pattern:
    console: '[%d{dd/MM/yy HH:mm:ss:SSS z}] %t %5p %c{2} [%X{traceId:-}, %X{spanId:-}]: %m%n'


