server:
  port: 8081

application:
  kafka:
    topic: "orders"

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:maindb
  flyway:
    enabled: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: "127.0.0.1:9092"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "metrics,health,logfile,flyway"
  health:
    defaults:
      enabled: true

logging:
  file:
    name: ./logs/order.log
  level:
    org.flywaydb: debug


